services:
  appsmith:
    image: appsmith/appsmith-ee:${APPSMITH_VERSION}
    container_name: appsmith
    hostname: appsmith
    restart: unless-stopped
    ports:
      - "${APPSMITH_PORT}:80"
    depends_on:
      - mongodb
      - redis
    volumes:
      - appsmith-data:/appsmith-stacks

  mongodb:
    image: mongo:${MONGODB_VERSION}
    container_name: appsmith-mongodb
    hostname: appsmith-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - appsmith-mongodb-data:/data/db

  redis:
    image: redis:${REDIS_VERSION}
    container_name: appsmith-redis
    hostname: appsmith-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - appsmith-redis-data:/data

volumes:
  appsmith-data:
  appsmith-mongodb-data:
  appsmith-redis-data:
